### ISSUE TITLE
Broken link -- from IITS Koeln home page

### ISSUE THREAD

**Issue by chandrasekharanr** [sanskrit-lexicon/VCP#8]
If I click on Vacaspatyam link, I get a "Document not found" page --

https://www.sanskrit-lexicon.uni-koeln.de/scans/VCPScan/2020/web/index.php

(The above is the link)

**Comment by funderburkjim** [comment]
We are using VCP as a test dictionary for some rearranging.
The link you mention above is now fixed.

Please continue to add problems that you notice with VCP in this issue.

Note, I just happened to see your note while working with new VCP --- normally a correction will not be as fast.

As a temporary fallback,  you might be able to get at the old version by changing the url to use '2013' instead of the current experimental '2020'.

**Comment by drdhaval2785** [comment]
Advance display not working in VCP 2020.

ERROR is
Could not open Dictionary 'query_dump.txt'

**Comment by funderburkjim** [comment]
## Back to VCPScan/2013

The homepage link has been reverted to VCPScan/2013 from VCPScan/2020.
VCPScan/2020 to remain as testbed.

**Comment by drdhaval2785** [comment]
https://www.sanskrit-lexicon.uni-koeln.de/scans/VCPScan/2020/web/webtc2/index.php works with 2020 data and working fine. Closing this.

**Comment by gasyoun** [comment]
> homepage link has been reverted to VCPScan/2013 from VCPScan/2020. VCPScan/2020 to remain as testbed for vcp-minimal 

Guess testing had ceased.
